### ISSUE TITLE
question about place right/left operator

### ISSUE THREAD

**Issue by veriatl** [classicwuhao/Cyclone#16]
according to: https://classicwuhao.github.io/cyclone_tutorial/expr/place-right-op.html

a generated path: `S6->S3->S4->S5->S1` satisfy the constraint: `<<S1 && <<2(S3->S4)` 

may I ask how this is counted? if counted from right to left, the sub-path `s3->s4` start at the index 3

**Comment by classicwuhao** [comment]
<< place operator places a node or a path at a specified position. This position is calculated from right to left, starting from 0.

- <<S1 : no explicit index value is given here. hence, S1 is placed on the rightmost of a path (to be discovered).
- <<2(S3->S4): is a sub path (no longer a node) and it contains its own length (=2). The index value of 2 is explicitly given here. Thus, the compiler places S3->S4 from right to left starting from 2 (counting from right to left) till the beginning node of the this sub path. In this case, it is S3 (S3 starting at index 3).

A slightly more detailed explanation can be found here (Example 5) :  https://classicwuhao.github.io/cyclone_tutorial/tutorial-basics-6.html

A more intuitive note: If you think place S3->S4 from left to right, then <<(S3->S4) wont make sense anymore because it is impossible.  You have to use <<1(S3->S4) to do this. Then what about <<0(S3->S4), since index value starts from 0. Thus, S3->S4 is placed from right to left in a path. This is consistent with >>(S3->S4). 0 always means the very beginning of a path no matter which direction you start from.

Hope this explains.

**Comment by veriatl** [comment]
ok, so the sub-path condition `<<2(S3->S4)` should also read from right to left. thanks
